/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-05-21 09:49:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ansari.*;
import java.util.List;
import java.util.ArrayList;

public final class AddNewStud_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/ViewStudList.jsp", Long.valueOf(1653114494948L));
    _jspx_dependants.put("/admindashboard.jsp", Long.valueOf(1653125537766L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("ansari");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("<h3 style=\"Color:blue\">Learner's Academy</h3>\r\n");
      out.write("<h4 style=\"Color:brown\">Welcome To Admin Dashboard</h4>\r\n");
      out.write("<hr>\r\n");
      out.write("<h5 style=\"Color:green\">Add New Student</h5>\r\n");
      out.write("</div>\r\n");
      out.write("<form action=\"insertStudent.jsp\" method=\"post\">\r\n");
      out.write("<table   style=\"text-align:center;  margin-left:auto;margin-right:auto;\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Student Id<br>\r\n");
      out.write("<input type=\"text\" name=\"sid\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>First Name<br>\r\n");
      out.write("<input type=\"text\" name=\"sfirstname\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Last Name<br>\r\n");
      out.write("<input type=\"text\" name=\"slastname\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Date Of Birth<br>\r\n");
      out.write("<input type=\"text\" name=\"sdob\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Address<br>\r\n");
      out.write("<input type=\"text\" name=\"saddress\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Phone<br>\r\n");
      out.write("<input type=\"text\" name=\"sphone\"></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("</table>\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("<h3 style=\"Color:blue\"><input type=\"submit\" value=\"Save\"></h3>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("<p align=center>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- \r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("<h3 style=\"Color:blue\">Learner's Academy</h3>\r\n");
      out.write("<h4 style=\"Color:brown\">Welcome To Admin Dashboard</h4>\r\n");
      out.write("</div>\r\n");
      out.write("<h1>View Student List</h1>\r\n");
      out.write("\r\n");
      out.write("<p align=center>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("<h3 style=\"Color:blue\">Learner's Academy</h3>\r\n");
      out.write("<h4 style=\"Color:brown\">Welcome To Admin Dashboard</h4>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("<form action=\"index.jsp\" method=\"post\">\r\n");
      out.write("<table  border=\"2\" style=\"text-align:center;  margin-left:auto;margin-right:auto;\" >\r\n");
      out.write("<tr>\r\n");
      out.write("<th style=\"background:Black;color:white\">S.No</th>\r\n");
      out.write("<th style=\"background:Black;color:white\">Task</th>\r\n");
      out.write("<th style=\"background:Black;color:white\" colspan=6>Action</th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th style=\"background:Black;color:white\">1</th>\r\n");
      out.write("<th style=\"background:Black;color:white\">Class</th>\r\n");
      out.write("<td><a href=\"ViewClassList.jsp\">View List</a></td>\r\n");
      out.write("<td><a href=\"AddNewClass.jsp\">Add New</a></td>\r\n");
      out.write("<td align=center><a href=\"editclass.jsp\">Edit</a></td>\r\n");
      out.write("<td align=center><a href=\"deleteclass.jsp\">Delete</a></td>\r\n");
      out.write("<td align=center><a href=\"assignSubandTeacher.jsp\">Teachers & Subject</a></td>\r\n");
      out.write("<td align=center><a href=\"classReport.jsp\">Report</a></td>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th style=\"background:Black;color:white\">2</th>\r\n");
      out.write("<th style=\"background:Black;color:white\">Student</th>\r\n");
      out.write("<td><a href=\"ViewStudList.jsp\">View List</a></td>\r\n");
      out.write("<td><a href=\"AddNewStud.jsp\">Add New</a></td>\r\n");
      out.write("<td><a href=\"EditStud.jsp\">Edit</a></td>\r\n");
      out.write("<td><a href=\"DeleteStud.jsp\">Delete</a></td>\r\n");
      out.write("<td><a href=\"AssignStudToClass.jsp\">Assign Class</a></td>\r\n");
      out.write("<td align=center><a href=\"#\"></a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th style=\"background:Black;color:white\">3</th>\r\n");
      out.write("<th style=\"background:Black;color:white\">Subjects</th>\r\n");
      out.write("<td><a href=\"ViewSubList.jsp\">View List</a></td>\r\n");
      out.write("<td><a href=\"AddNewSub.jsp\">Add New</a></td>\r\n");
      out.write("<td><a href=\"EditSub.jsp\">Edit</a></td>\r\n");
      out.write("<td><a href=\"DeleteSub.jsp\">Delete</a></td>\r\n");
      out.write("<td><a href=\"#\"></a></td>\r\n");
      out.write("<td align=center><a href=#\"></a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<th style=\"background:Black;color:white\">4</th>\r\n");
      out.write("<th style=\"background:Black;color:white\">Teachers</th>\r\n");
      out.write("<td><a href=\"ViewTeacherList.jsp\">View List</a></td>\r\n");
      out.write("<td><a href=\"AddNewTeacher.jsp\">Add New</a></td>\r\n");
      out.write("<td><a href=\"EditTeacher.jsp\">Edit</a></td>\r\n");
      out.write("<td><a href=\"DeleteTeacher.jsp\">Delete</a></td>\r\n");
      out.write("<td><a href=\"#\"></a></td>\r\n");
      out.write("<td align=center><a href=\"#\"></a></td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("<h3 style=\"Color:blue\"><input type=\"submit\" value=\"Logout\"></h3>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("</p>\r\n");
      out.write("-->\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("<h5 style=\"Color:green\">List Of Students</h5>\r\n");
      out.write("</div>\r\n");
      out.write("<form action=\"admindashboard.jsp\" method=\"post\">\r\n");
      out.write("<table align=center border=1>\r\n");
 StudentDAO dao=new StudentDAO();
List<Student> studentpojo=(List<Student>)dao.view();

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<th>Student Id</th>\r\n");
      out.write("<th>First Name</th>\r\n");
      out.write("<th>Last Name</th>\r\n");
      out.write("<th>Date Of Birth</th>\r\n");
      out.write("<th>Address</th>\r\n");
      out.write("<th>Phone</th>\r\n");
      out.write("<th>Class Name</th>\r\n");
      out.write("<th colspan=9>Action</th>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
 for(Student c:studentpojo){ 
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td align=center>");
      out.print(c.getSid());
      out.write("</td>\r\n");
      out.write("<td align=center>");
      out.print(c.getsFirstName());
      out.write("</td>\r\n");
      out.write("<td align=center>");
      out.print(c.getsLastName());
      out.write("</td>\r\n");
      out.write("<td align=center>");
      out.print(c.getsDob());
      out.write("</td>\r\n");
      out.write("<td align=center>");
      out.print(c.getsAddress());
      out.write("</td>\r\n");
      out.write("<td align=center>");
      out.print(c.getsPhone());
      out.write("</td>\r\n");
      out.write("<td align=center>");
      out.print(c.getsClass());
      out.write("</td>\r\n");
      out.write("<td align=center><a href=\"edit.jsp\">Edit</a></td>\r\n");
      out.write("<td align=center><a href=\"delete.jsp\">Delete</a></td>\r\n");
      out.write("</tr>\r\n");
} 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("<h3 style=\"Color:blue\"><input type=\"submit\" value=\"Back To Dashboard\"></h3>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("</p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
