/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-05-20 18:04:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ansari.*;
import java.util.*;
import java.io.*;

public final class assignSubandTeacher_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("ansari");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("<h3 style=\"Color:blue\">Learner's Academy</h3>\r\n");
      out.write("<h4 style=\"Color:brown\">Welcome To Admin Dashboard</h4>\r\n");
      out.write("</div><hr>\r\n");
      out.write("<div  style=\"text-align:center;\">\r\n");
      out.write("<h4 style=\"Color:green\"><u>Assign Subject And Teachers To A Class</u></h4>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<form action=\"insertSubjectAndTeacher.jsp\" method=\"post\">\r\n");
      out.write("<table   style=\"text-align:center;  margin-left:auto;margin-right:auto;\">\r\n");
 ClassDAO dao1=new ClassDAO();
List<ClassForStudent> classpojo=(List<ClassForStudent>)dao1.viewName();

      out.write("\r\n");
      out.write("\r\n");
 SubjectDAO dao3=new SubjectDAO();
List<Subjects> subpojo=(List<Subjects>)dao3.viewName();

      out.write("\r\n");
      out.write("\r\n");
 TeachersDAO dao2=new TeachersDAO();
List<Teachers> teacherpojo=(List<Teachers>)dao2.viewName();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Select Class\r\n");
      out.write("<Select name=\"class1\">\r\n");
 for(ClassForStudent c1:classpojo){ 
      out.write("  \r\n");
      out.write("<option>\r\n");
      out.print(c1.getClassName());
      out.write("\r\n");
      out.write("</option>\r\n");
} 
      out.write("\r\n");
      out.write("</Select>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Select Subject\r\n");
      out.write("<Select name=\"subject1\">\r\n");
 for(Subjects s1:subpojo){ 
      out.write("  \r\n");
      out.write("<option>\r\n");
      out.print(s1.getSubjectName());
      out.write("\r\n");
      out.write("</option>\r\n");
} 
      out.write("\r\n");
      out.write("</Select>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("<td>Select Teacher\r\n");
      out.write("<Select name=\"teacher1\">\r\n");
 for(Teachers t1:teacherpojo){ 
      out.write("  \r\n");
      out.write("<option>\r\n");
      out.print(t1.gettFirstName());
      out.write("\r\n");
      out.write("</option>\r\n");
} 
      out.write("\r\n");
      out.write("</Select>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("<h3 style=\"Color:blue\"><input type=\"submit\" value=\"Assign\"></h3>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("<h3 style=\"Color:blue\"><a href=\"admindashboard.jsp\"><input type=\"submit\" value=\"Back To Dashboard\"></a></h3>\r\n");
      out.write("</div> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
